### ISSUE TITLE
Remove .classpath and .project files

### ISSUE THREAD

**Issue by diego2013** [dbagshaw/DDSsmartcardio#2]
Eclipse has two configuration files _.classpath_ and _.project_ for each project, but these two files should not be shared via repository. Classpath routes are different for each user and is not a good practice to include them. New "project cloners" would have to overwrite these files to establish their own configuration when importing the project in eclipse.

![image](https://cloud.githubusercontent.com/assets/4389491/13185003/feec34c4-d70c-11e5-8d6a-ff064cbb9b7c.png)

**Comment by diego2013** [comment]
I removed these two files from the git index with

```
git rm --cached .project
git rm --cached .classpath
```

![image](https://cloud.githubusercontent.com/assets/4389491/13185140/9348f74c-d70d-11e5-9e7e-19f51c8a66f6.png)

then make git ignore them by adding their names to the _.gitingore_ file.

**Comment by dbagshaw** [comment]
Thank you. I did not realized that those got included. I must have included them by accident!

Dylan

**Comment by diego2013** [comment]
I think I actually see too *.sql files from the _target_ directory (two last lines of the screenshot). I see no compiled classes should be there either. 

Let me know if you see anything from the _target/_ directory on your git index tree.

![image](https://cloud.githubusercontent.com/assets/4389491/13187425/e8772ea4-d718-11e5-86aa-1d799f09964f.png)
